export const CATEGORIAS = {
  rosa: {
    id: 'rosa',
    nombre: 'Sin Censura (100% Explícito)',
    color: '#f43f5e',
    icono: '🩷',
    apuestas: [
      '🔗 Sumisión & Ataduras (20 min sin hablar)',
      '🔞 Espectáculo de Autoestimulación (Ganador marca ritmo)',
      '🍑 Acceso Sin Restricciones (Anal / Juguetes a elección)',
      '🚫 Edging & Control del Orgasmo (3 límites antes del final)',
      '🧎 Servidumbre / Oral Guiado',
      '👅 Oral Sin Prisa (mínimo 15 min, el ganador dirige)',
      '🎥 Grabación Privada (solo para vosotros, escena a elección del ganador)',
      '🪢 Bondage Ligero con Pañuelos (postura a elección del ganador)',
      '🍆 Juguete Sorpresa (el ganador elige cuál y cómo se usa)',
      '🌶️ Sexo con Instrucciones en Voz Alta (el ganador narra qué quiere)',
      '🙈 Venda en los Ojos + Órdenes Susurradas',
      '🔥 Striptease Lento a Cámara Lenta',
      '💦 Postura Favorita del Ganador, sin negociación',
      '👐 Manos Atadas Detrás de la Espalda Durante el Sexo',
      '🕯️ Sesión con Cera o Hielo (dentro de límites acordados)',
      '📍 Elige el Lugar de la Casa, ahora mismo',
      '🎭 Rol Sexual a Elección del Ganador',
    ],
  },
  rojo: {
    id: 'rojo',
    nombre: 'Retos & Provocación',
    color: '#ef4444',
    icono: '🔴',
    apuestas: [
      '👗 Dictador/a de Lencería / Ausencia de ropa interior',
      '📸 Foto Efímera Sin Censura In Situ (5 segundos)',
      '🤫 El Secreto en Público (Juguete a distancia en salida)',
      '🎙️ Audio en Bucle / Gemido Real desinhibido',
      '🚷 Tacto Prohibido en Casa durante 1 hora',
      '💋 Beso Robado Delante de Gente, sin que se note el motivo',
      '📱 3 Mensajes Subidos de Tono Durante el Día, cuando el ganador quiera',
      '👀 Duelo de Miradas: pierde quien aparte la vista primero',
      '🍒 Elige Qué Ropa Interior Lleva Hoy el Perdedor',
      '🎲 Prenda Sorpresa: quitarse una prenda a elección del ganador, ahora',
      '🕺 Baile Sexy de 1 Minuto a Petición',
      '🔊 Confesión en Voz Alta de una Fantasía',
      '📸 Foto Provocativa (no explícita) de Fondo de Pantalla 24h',
      '🚗 Reto en el Coche: mano quieta en la pierna todo el trayecto',
      '🍾 Shot de Provocación: reto improvisado esa misma noche',
      '🎯 Verdad Incómoda: responder algo picante sin evasivas',
    ],
  },
  morado: {
    id: 'morado',
    nombre: 'Deseos & Experiencias',
    color: '#a855f7',
    icono: '🟣',
    apuestas: [
      '🥂 Cita a Ciegas con Mando Total',
      '🛍️ Inversión Erótica / Capricho de la lista',
      '🏨 Escapada con 3 Reglas Especiales',
      '🎭 Noche de Rol & Temática Completa',
      '🎬 Sesión de Cine Privado + Recreación',
      '🌅 Escapada de Un Día Sorpresa (destino a elección del ganador)',
      '🍽️ Cena Temática Completa (el ganador elige el tema)',
      '🎡 Plan Cumplido de la Lista de Deseos Pendientes',
      '🛁 Noche de Baño Compartido, velas y sin móviles',
      '🎶 Playlist + Baile Lento Solo Para Vosotros',
      '🗺️ Aventura Sorpresa Organizada en Secreto',
      '🎁 Regalo Experiencia, pequeño pero elegido con mimo',
      '🌌 Noche de Terraza o Estrellas, plan tranquilo a elección',
      '🍷 Cata a Ciegas (vinos, postres o lo que proponga el ganador)',
      '📖 Capítulo Nuevo: probar algo de la lista de fantasías pendientes',
    ],
  },
  azul: {
    id: 'azul',
    nombre: 'Día a Día & Complicidad',
    color: '#3b82f6',
    icono: '🔵',
    apuestas: [
      '👑 Servidor/a del Hogar (24 horas)',
      '💆 Masaje Corporal Profundo de 30 min',
      '📺 Mando a Distancia & Menú Absoluto',
      '☕ Desayuno VIP en la Cama',
      '🛏️ Mimos y Caricias sin Contraprestación',
      '🧺 Colada + Plancha de la Semana',
      '🍳 Cena Preparada Sin Rechistar (menú a elección)',
      '🚗 Chófer Personal Durante 2 Días',
      '🧹 Limpieza Express de la Casa a Elección',
      '📵 Sin Móvil 2 Horas: atención 100% al ganador',
      '🐶 Encargado/a de Todas las Tareas del Día',
      '🛌 Elige Qué Vemos Esta Noche Sin Discusión',
      '🎧 Media Hora de Silencio y Tranquilidad Total, a su gusto',
      '🧦 Recoger y Ordenar Su Lado del Armario',
      '🥐 Sorpresa Random: un detalle pequeño elegido con cariño',
    ],
  },
}

export const ORDEN_CATEGORIAS = ['rosa', 'rojo', 'morado', 'azul']
